<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAehvZyz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAehvZyz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAehvZyz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAehvZyz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAehvZyz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AehvZyz',
    'container.build_id' => 'fa32a3f9',
    'container.build_time' => 1560786337,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAehvZyz');
