<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMySctWf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMySctWf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMySctWf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMySctWf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMySctWf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MySctWf',
    'container.build_id' => '3a01a6b7',
    'container.build_time' => 1557763609,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMySctWf');
