<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerENviuxB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerENviuxB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerENviuxB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerENviuxB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerENviuxB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ENviuxB',
    'container.build_id' => 'ffec5472',
    'container.build_time' => 1559575021,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerENviuxB');
